apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter-template.fullname" . }}
  labels:
    {{- include "jupyter-template.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.spark.ui.enabled }}
    - name: spark-ui
      port: {{ .Values.spark.ui.port }}
      targetPort: spark-ui
      protocol: TCP
    {{- end }}
  selector:
    {{- include "jupyter-template.selectorLabels" . | nindent 4 }}